import { ProjectData } from '../types';

export const SAMPLE_PROJECTS: { id: string; name: string; tag: string; data: ProjectData }[] = [
  {
    id: 'qua-khu-anh-khong-the-quen',
    name: 'Quá Khứ Anh Không Thể Quên - AI Bespoke',
    tag: 'Ballad Soul',
    data: {
      title: 'Quá Khứ Anh Không Thể Quên',
      artist: 'Dương Minh Tuấn',
      channelLogoText: '✦ AI DIRECTOR CUT',
      layoutMode: 'generative_ai',
      generativeLayout: {
        artworkDisplay: {
          mode: 'side_card',
          shape: 'rounded_square',
          scale: 0.44,
          glowColor: '#38BDF8',
          glowBlur: 24,
          showViewfinderCorners: true,
          showVinylGrooves: false,
          rotationEffect: 'tilt_breath',
        },
        lyricsDisplay: {
          placement: 'right_side',
          alignment: 'left',
          linesCount: 4,
          showActiveAccentBar: true,
          accentBarColor: '#38BDF8',
        },
        visualizerPlacement: {
          position: 'under_artwork',
          style: 'bars',
          color: '#38BDF8',
        },
        branding: {
          showTrackBadge: true,
          trackBadgeText: 'AI MASTERPIECE',
          titlePlacement: 'above_lyrics',
        },
      },
      audioUrl: '',
      audioDuration: 24,
      aspectRatio: '16:9',
      background: {
        imageUrl:
          'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1080&q=80',
        effect: 'clean_cinematic',
        dimOpacity: 0.5,
        blurAmount: 10,
        filter: 'cinematic_teal',
      },
      typography: {
        fontFamily: 'Orbitron',
        fontSize: 32,
        textColor: '#FFFFFF',
        highlightColor: '#38BDF8',
        secondaryColor: '#94A3B8',
        textShadow: true,
        textStroke: false,
        strokeColor: '#000000',
        letterSpacing: 2,
        textCase: 'normal',
        textAlign: 'left',
        kineticEffect: 'emotional_soul',
        emotionalSparkles: true,
      },
      visualizer: {
        type: 'none',
        color: '#38BDF8',
        opacity: 0.8,
        barCount: 28,
      },
      lyrics: [
        {
          id: 'q1',
          text: 'Quá khứ anh chẳng thể nào quên',
          startTime: 1.0,
          endTime: 4.8,
          words: [
            { text: 'Quá', startTime: 1.0, endTime: 1.5 },
            { text: 'khứ', startTime: 1.5, endTime: 2.1 },
            { text: 'anh', startTime: 2.1, endTime: 2.7 },
            { text: 'chẳng thể nào', startTime: 2.7, endTime: 4.0 },
            { text: 'quên', startTime: 4.0, endTime: 4.8 },
          ],
        },
        {
          id: 'q2',
          text: 'Bởi vì anh không mong đôi ta chia ly',
          startTime: 5.0,
          endTime: 9.2,
          words: [
            { text: 'Bởi vì', startTime: 5.0, endTime: 5.8 },
            { text: 'anh', startTime: 5.8, endTime: 6.4 },
            { text: 'không mong', startTime: 6.4, endTime: 7.5 },
            { text: 'đôi ta', startTime: 7.5, endTime: 8.3 },
            { text: 'chia ly', startTime: 8.3, endTime: 9.2 },
          ],
        },
        {
          id: 'q3',
          text: 'Ngồi nhớ em anh lặng nhìn mây',
          startTime: 9.5,
          endTime: 13.5,
          words: [
            { text: 'Ngồi', startTime: 9.5, endTime: 10.1 },
            { text: 'nhớ em', startTime: 10.1, endTime: 11.2 },
            { text: 'anh', startTime: 11.2, endTime: 11.7 },
            { text: 'lặng nhìn', startTime: 11.7, endTime: 12.7 },
            { text: 'mây', startTime: 12.7, endTime: 13.5 },
          ],
        },
        {
          id: 'q4',
          text: 'Mây trôi đi về đâu không thể giữ lấy',
          startTime: 13.8,
          endTime: 17.8,
          words: [
            { text: 'Mây', startTime: 13.8, endTime: 14.3 },
            { text: 'trôi đi', startTime: 14.3, endTime: 15.2 },
            { text: 'về đâu', startTime: 15.2, endTime: 16.1 },
            { text: 'không thể', startTime: 16.1, endTime: 17.0 },
            { text: 'giữ lấy', startTime: 17.0, endTime: 17.8 },
          ],
        },
        {
          id: 'q5',
          text: 'Ôm hoài những kỷ niệm đã cũ',
          startTime: 18.0,
          endTime: 21.0,
          words: [
            { text: 'Ôm hoài', startTime: 18.0, endTime: 18.8 },
            { text: 'những', startTime: 18.8, endTime: 19.3 },
            { text: 'kỷ niệm', startTime: 19.3, endTime: 20.2 },
            { text: 'đã cũ', startTime: 20.2, endTime: 21.0 },
          ],
        },
        {
          id: 'q6',
          text: 'Lẩn trốn mình trong mộng dài thiên thu',
          startTime: 21.2,
          endTime: 24.0,
          words: [
            { text: 'Lẩn trốn', startTime: 21.2, endTime: 22.0 },
            { text: 'mình trong', startTime: 22.0, endTime: 22.8 },
            { text: 'mộng dài', startTime: 22.8, endTime: 23.4 },
            { text: 'thiên thu', startTime: 23.4, endTime: 24.0 },
          ],
        },
      ],
    },
  },
  {
    id: 'tung-quen-chill',
    name: 'Từng Quen - Chill Indie Pop',
    tag: 'Vietnamese Indie',
    data: {
      title: 'Từng Quen',
      artist: 'Wren Evans & Vũ (Demo Vibe)',
      audioUrl: '', // Will be injected by procedural generator
      audioDuration: 24,
      aspectRatio: '9:16',
      background: {
        imageUrl:
          'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1080&q=80',
        effect: 'ken_burns',
        dimOpacity: 0.45,
        blurAmount: 2,
        filter: 'sunset',
      },
      typography: {
        fontFamily: 'Syne',
        fontSize: 34,
        textColor: '#FFFFFF',
        highlightColor: '#F43F5E',
        secondaryColor: '#FDA4AF',
        textShadow: true,
        textStroke: false,
        strokeColor: '#000000',
        letterSpacing: 1,
        textCase: 'uppercase',
        textAlign: 'center',
        kineticEffect: 'karaoke_glow',
      },
      visualizer: {
        type: 'bars',
        color: '#F43F5E',
        opacity: 0.85,
        barCount: 28,
      },
      lyrics: [
        {
          id: 'l1',
          text: 'Từng là hạt mưa rơi trên vai em dịu êm',
          startTime: 0.5,
          endTime: 4.2,
          words: [
            { text: 'Từng', startTime: 0.5, endTime: 1.0 },
            { text: 'là', startTime: 1.0, endTime: 1.4 },
            { text: 'hạt', startTime: 1.4, endTime: 1.8 },
            { text: 'mưa', startTime: 1.8, endTime: 2.3 },
            { text: 'rơi', startTime: 2.3, endTime: 2.7 },
            { text: 'trên', startTime: 2.7, endTime: 3.1 },
            { text: 'vai', startTime: 3.1, endTime: 3.6 },
            { text: 'em', startTime: 3.6, endTime: 3.9 },
            { text: 'dịu êm', startTime: 3.9, endTime: 4.2 },
          ],
        },
        {
          id: 'l2',
          text: 'Từng là hoàng hôn buông lơi góc phố quen',
          startTime: 4.4,
          endTime: 8.0,
          words: [
            { text: 'Từng', startTime: 4.4, endTime: 4.9 },
            { text: 'là', startTime: 4.9, endTime: 5.3 },
            { text: 'hoàng', startTime: 5.3, endTime: 5.8 },
            { text: 'hôn', startTime: 5.8, endTime: 6.2 },
            { text: 'buông', startTime: 6.2, endTime: 6.6 },
            { text: 'lơi', startTime: 6.6, endTime: 7.0 },
            { text: 'góc', startTime: 7.0, endTime: 7.3 },
            { text: 'phố', startTime: 7.3, endTime: 7.7 },
            { text: 'quen', startTime: 7.7, endTime: 8.0 },
          ],
        },
        {
          id: 'l3',
          text: 'Đoạn đường ngày xưa ta chung đôi chung lối về',
          startTime: 8.2,
          endTime: 12.0,
          words: [
            { text: 'Đoạn', startTime: 8.2, endTime: 8.6 },
            { text: 'đường', startTime: 8.6, endTime: 9.1 },
            { text: 'ngày', startTime: 9.1, endTime: 9.5 },
            { text: 'xưa', startTime: 9.5, endTime: 10.0 },
            { text: 'ta', startTime: 10.0, endTime: 10.4 },
            { text: 'chung đôi', startTime: 10.4, endTime: 11.2 },
            { text: 'chung', startTime: 11.2, endTime: 11.6 },
            { text: 'lối về', startTime: 11.6, endTime: 12.0 },
          ],
        },
        {
          id: 'l4',
          text: 'Giờ chỉ còn anh với bao giấc mơ xa xôi',
          startTime: 12.2,
          endTime: 16.0,
          words: [
            { text: 'Giờ', startTime: 12.2, endTime: 12.7 },
            { text: 'chỉ', startTime: 12.7, endTime: 13.1 },
            { text: 'còn', startTime: 13.1, endTime: 13.6 },
            { text: 'anh', startTime: 13.6, endTime: 14.1 },
            { text: 'với bao', startTime: 14.1, endTime: 14.7 },
            { text: 'giấc', startTime: 14.7, endTime: 15.1 },
            { text: 'mơ', startTime: 15.1, endTime: 15.5 },
            { text: 'xa xôi', startTime: 15.5, endTime: 16.0 },
          ],
        },
        {
          id: 'l5',
          text: 'Gió mang theo bao yêu dấu hôm nào',
          startTime: 16.2,
          endTime: 20.0,
          words: [
            { text: 'Gió', startTime: 16.2, endTime: 16.8 },
            { text: 'mang', startTime: 16.8, endTime: 17.3 },
            { text: 'theo', startTime: 17.3, endTime: 17.8 },
            { text: 'bao', startTime: 17.8, endTime: 18.3 },
            { text: 'yêu', startTime: 18.3, endTime: 18.9 },
            { text: 'dấu', startTime: 18.9, endTime: 19.4 },
            { text: 'hôm nào', startTime: 19.4, endTime: 20.0 },
          ],
        },
        {
          id: 'l6',
          text: 'Để lại mình anh cùng muôn nỗi nhớ vương',
          startTime: 20.2,
          endTime: 24.0,
          words: [
            { text: 'Để', startTime: 20.2, endTime: 20.7 },
            { text: 'lại', startTime: 20.7, endTime: 21.2 },
            { text: 'mình anh', startTime: 21.2, endTime: 22.0 },
            { text: 'cùng', startTime: 22.0, endTime: 22.4 },
            { text: 'muôn', startTime: 22.4, endTime: 22.9 },
            { text: 'nỗi nhớ', startTime: 22.9, endTime: 23.5 },
            { text: 'vương', startTime: 23.5, endTime: 24.0 },
          ],
        },
      ],
    },
  },
  {
    id: 'cyber-neon-night',
    name: 'Cyber Neon - Synthwave Pulse',
    tag: 'Synthwave EDM',
    data: {
      title: 'Neon Horizon',
      artist: 'Kavinsky & CyberPulse',
      channelLogoText: '⚡ CYBER PULSE',
      layoutMode: 'generative_ai',
      generativeLayout: {
        artworkDisplay: {
          mode: 'floating_vinyl',
          shape: 'circle_vinyl',
          scale: 0.42,
          glowColor: '#06B6D4',
          glowBlur: 30,
          showViewfinderCorners: false,
          showVinylGrooves: true,
          rotationEffect: 'slow_spin',
        },
        lyricsDisplay: {
          placement: 'bottom_cinematic',
          alignment: 'center',
          linesCount: 2,
          showActiveAccentBar: false,
          accentBarColor: '#F43F5E',
        },
        visualizerPlacement: {
          position: 'around_artwork',
          style: 'ring',
          color: '#06B6D4',
        },
        branding: {
          showTrackBadge: true,
          trackBadgeText: 'CYBER DIMENSION',
          titlePlacement: 'top_center',
        },
      },
      audioUrl: '',
      audioDuration: 24,
      aspectRatio: '9:16',
      background: {
        imageUrl:
          'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1080&q=80',
        effect: 'bass_pulse',
        dimOpacity: 0.35,
        blurAmount: 0,
        filter: 'cyberpunk',
      },
      typography: {
        fontFamily: 'Bebas Neue',
        fontSize: 42,
        textColor: '#06B6D4',
        highlightColor: '#F43F5E',
        secondaryColor: '#E0E7FF',
        textShadow: true,
        textStroke: true,
        strokeColor: '#000000',
        letterSpacing: 2,
        textCase: 'uppercase',
        textAlign: 'center',
        kineticEffect: 'neon_pulse',
      },
      visualizer: {
        type: 'wave',
        color: '#06B6D4',
        opacity: 0.9,
        barCount: 32,
      },
      lyrics: [
        {
          id: 'c1',
          text: 'LOST IN THE DIGITAL RAIN AT 2 AM',
          startTime: 0.5,
          endTime: 4.0,
          words: [
            { text: 'LOST', startTime: 0.5, endTime: 1.2 },
            { text: 'IN THE', startTime: 1.2, endTime: 2.0 },
            { text: 'DIGITAL', startTime: 2.0, endTime: 2.8 },
            { text: 'RAIN', startTime: 2.8, endTime: 3.4 },
            { text: 'AT 2 AM', startTime: 3.4, endTime: 4.0 },
          ],
        },
        {
          id: 'c2',
          text: 'SPEEDING THROUGH NEON HIGHWAYS TONIGHT',
          startTime: 4.2,
          endTime: 8.0,
          words: [
            { text: 'SPEEDING', startTime: 4.2, endTime: 5.1 },
            { text: 'THROUGH', startTime: 5.1, endTime: 5.8 },
            { text: 'NEON', startTime: 5.8, endTime: 6.6 },
            { text: 'HIGHWAYS', startTime: 6.6, endTime: 7.3 },
            { text: 'TONIGHT', startTime: 7.3, endTime: 8.0 },
          ],
        },
        {
          id: 'c3',
          text: 'FEEL THE 808 BASS IN YOUR CHEST',
          startTime: 8.2,
          endTime: 12.0,
          words: [
            { text: 'FEEL', startTime: 8.2, endTime: 8.9 },
            { text: 'THE', startTime: 8.9, endTime: 9.4 },
            { text: '808 BASS', startTime: 9.4, endTime: 10.6 },
            { text: 'IN YOUR', startTime: 10.6, endTime: 11.2 },
            { text: 'CHEST', startTime: 11.2, endTime: 12.0 },
          ],
        },
        {
          id: 'c4',
          text: 'NEVER LOOKING BACK INTO THE DARK',
          startTime: 12.2,
          endTime: 16.0,
          words: [
            { text: 'NEVER', startTime: 12.2, endTime: 13.0 },
            { text: 'LOOKING', startTime: 13.0, endTime: 13.8 },
            { text: 'BACK', startTime: 13.8, endTime: 14.5 },
            { text: 'INTO', startTime: 14.5, endTime: 15.2 },
            { text: 'THE DARK', startTime: 15.2, endTime: 16.0 },
          ],
        },
        {
          id: 'c5',
          text: 'ELECTRIC ECHOES CALLING OUT YOUR NAME',
          startTime: 16.2,
          endTime: 20.0,
          words: [
            { text: 'ELECTRIC', startTime: 16.2, endTime: 17.2 },
            { text: 'ECHOES', startTime: 17.2, endTime: 18.0 },
            { text: 'CALLING', startTime: 18.0, endTime: 18.9 },
            { text: 'OUT YOUR', startTime: 18.9, endTime: 19.4 },
            { text: 'NAME', startTime: 19.4, endTime: 20.0 },
          ],
        },
        {
          id: 'c6',
          text: 'WE ARE IMMORTAL UNDER SYNTHWAVE SKIES',
          startTime: 20.2,
          endTime: 24.0,
          words: [
            { text: 'WE ARE', startTime: 20.2, endTime: 21.0 },
            { text: 'IMMORTAL', startTime: 21.0, endTime: 22.0 },
            { text: 'UNDER', startTime: 22.0, endTime: 22.8 },
            { text: 'SYNTHWAVE', startTime: 22.8, endTime: 23.4 },
            { text: 'SKIES', startTime: 23.4, endTime: 24.0 },
          ],
        },
      ],
    },
  },
  {
    id: 'lofi-coffee-acoustic',
    name: 'Coffee & Rain - Acoustic Lo-fi',
    tag: 'Acoustic / Lo-Fi',
    data: {
      title: 'Mưa Đầu Mùa',
      artist: 'Acoustic Sunset',
      channelLogoText: '☕ ACOUSTIC TAPE',
      layoutMode: 'generative_ai',
      generativeLayout: {
        artworkDisplay: {
          mode: 'polaroid_badge',
          shape: 'polaroid',
          scale: 0.42,
          glowColor: '#F59E0B',
          glowBlur: 20,
          showViewfinderCorners: false,
          showVinylGrooves: false,
          rotationEffect: 'tilt_breath',
        },
        lyricsDisplay: {
          placement: 'right_side',
          alignment: 'left',
          linesCount: 3,
          showActiveAccentBar: true,
          accentBarColor: '#F59E0B',
        },
        visualizerPlacement: {
          position: 'under_artwork',
          style: 'wave',
          color: '#F59E0B',
        },
        branding: {
          showTrackBadge: true,
          trackBadgeText: 'VINTAGE MEMORIES',
          titlePlacement: 'above_lyrics',
        },
      },
      audioUrl: '',
      audioDuration: 24,
      aspectRatio: '16:9',
      background: {
        imageUrl:
          'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1280&q=80',
        effect: 'particles_glow',
        dimOpacity: 0.5,
        blurAmount: 1,
        filter: 'vintage_warm',
      },
      typography: {
        fontFamily: 'Caveat',
        fontSize: 38,
        textColor: '#FEF3C7',
        highlightColor: '#F59E0B',
        secondaryColor: '#FCD34D',
        textShadow: true,
        textStroke: false,
        strokeColor: '#000000',
        letterSpacing: 1,
        textCase: 'normal',
        textAlign: 'center',
        kineticEffect: 'cinematic_fade',
      },
      visualizer: {
        type: 'circle',
        color: '#F59E0B',
        opacity: 0.75,
        barCount: 36,
      },
      lyrics: [
        {
          id: 'a1',
          text: 'Một tách cà phê ấm giữa chiều mưa rơi',
          startTime: 0.5,
          endTime: 4.5,
          words: [
            { text: 'Một', startTime: 0.5, endTime: 1.0 },
            { text: 'tách', startTime: 1.0, endTime: 1.5 },
            { text: 'cà phê', startTime: 1.5, endTime: 2.3 },
            { text: 'ấm', startTime: 2.3, endTime: 2.8 },
            { text: 'giữa chiều', startTime: 2.8, endTime: 3.6 },
            { text: 'mưa rơi', startTime: 3.6, endTime: 4.5 },
          ],
        },
        {
          id: 'a2',
          text: 'Nhìn qua khung cửa kính nghe tiếng lòng bình yên',
          startTime: 4.8,
          endTime: 9.5,
          words: [
            { text: 'Nhìn', startTime: 4.8, endTime: 5.4 },
            { text: 'qua', startTime: 5.4, endTime: 5.9 },
            { text: 'khung cửa', startTime: 5.9, endTime: 6.8 },
            { text: 'kính', startTime: 6.8, endTime: 7.4 },
            { text: 'nghe tiếng lòng', startTime: 7.4, endTime: 8.6 },
            { text: 'bình yên', startTime: 8.6, endTime: 9.5 },
          ],
        },
        {
          id: 'a3',
          text: 'Bản tình ca cũ ngân nga không vội vã',
          startTime: 9.8,
          endTime: 14.5,
          words: [
            { text: 'Bản', startTime: 9.8, endTime: 10.4 },
            { text: 'tình ca', startTime: 10.4, endTime: 11.5 },
            { text: 'cũ', startTime: 11.5, endTime: 12.0 },
            { text: 'ngân nga', startTime: 12.0, endTime: 13.2 },
            { text: 'không vội vã', startTime: 13.2, endTime: 14.5 },
          ],
        },
        {
          id: 'a4',
          text: 'Những kỷ niệm xưa như thước phim quay chậm',
          startTime: 14.8,
          endTime: 19.5,
          words: [
            { text: 'Những', startTime: 14.8, endTime: 15.3 },
            { text: 'kỷ niệm', startTime: 15.3, endTime: 16.3 },
            { text: 'xưa', startTime: 16.3, endTime: 17.0 },
            { text: 'như thước phim', startTime: 17.0, endTime: 18.4 },
            { text: 'quay chậm', startTime: 18.4, endTime: 19.5 },
          ],
        },
        {
          id: 'a5',
          text: 'Khép lại ngày dài bằng nụ cười an nhiên',
          startTime: 19.8,
          endTime: 24.0,
          words: [
            { text: 'Khép', startTime: 19.8, endTime: 20.4 },
            { text: 'lại', startTime: 20.4, endTime: 20.9 },
            { text: 'ngày dài', startTime: 20.9, endTime: 21.8 },
            { text: 'bằng', startTime: 21.8, endTime: 22.3 },
            { text: 'nụ cười', startTime: 22.3, endTime: 23.2 },
            { text: 'an nhiên', startTime: 23.2, endTime: 24.0 },
          ],
        },
      ],
    },
  },
];
